// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATE9tXW-gV8eTSEc87sZ0w8h0OY6bAWaU',
    appId: '1:286679303219:web:d1afaf6eb7e83c8afe0f46',
    messagingSenderId: '286679303219',
    projectId: 'lab-app-31aaf',
    authDomain: 'lab-app-31aaf.firebaseapp.com',
    storageBucket: 'lab-app-31aaf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvXe-nDLoKx5iHitRhido4W9mjTDGUSlM',
    appId: '1:286679303219:android:5e9c257630e39929fe0f46',
    messagingSenderId: '286679303219',
    projectId: 'lab-app-31aaf',
    storageBucket: 'lab-app-31aaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh8pxYPuuy4kaCMluApk4Tm_xDrxgVNwQ',
    appId: '1:286679303219:ios:9d037dac6ae09279fe0f46',
    messagingSenderId: '286679303219',
    projectId: 'lab-app-31aaf',
    storageBucket: 'lab-app-31aaf.appspot.com',
    iosClientId: '286679303219-7k865fmb990i70ramuqin3vnjma56hn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.citycafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh8pxYPuuy4kaCMluApk4Tm_xDrxgVNwQ',
    appId: '1:286679303219:ios:9d037dac6ae09279fe0f46',
    messagingSenderId: '286679303219',
    projectId: 'lab-app-31aaf',
    storageBucket: 'lab-app-31aaf.appspot.com',
    iosClientId: '286679303219-7k865fmb990i70ramuqin3vnjma56hn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.citycafeApp',
  );
}
